# version: '3'
services:
  laravel.test:
    volumes:
      - ./:/var/www/html

  cron:
    image: sail-8.2/app
    depends_on:
      - laravel.test
    volumes:
      - ./:/var/www/html
    entrypoint: |
      bash -c 'while true; do
        php /var/www/html/artisan schedule:run >> /dev/null 2>&1
        sleep 60
      done'

  mysql:
    ports:
      - "3308:3306"

volumes: #<-追加した
  mutagen-sync:
    external: true